package demo;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Document implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String name;
   private Double actual;
   private Double required;

   public Document()
   {
   }

   public java.lang.String getName()
   {
      return this.name;
   }

   public void setName(java.lang.String name)
   {
      this.name = name;
   }

   public java.lang.Double getActual()
   {
      return this.actual;
   }

   public void setActual(java.lang.Double actual)
   {
      this.actual = actual;
   }

   public java.lang.Double getRequired()
   {
      return this.required;
   }

   public void setRequired(java.lang.Double required)
   {
      this.required = required;
   }

   public Document(java.lang.String name, java.lang.Double actual,
         java.lang.Double required)
   {
      this.name = name;
      this.actual = actual;
      this.required = required;
   }

}