package demo;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Evidence implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String phase;
   private java.lang.String milestone;
   private java.util.List<demo.Document> documents;
   private boolean approved;

   public Evidence()
   {
   }

   public java.lang.String getPhase()
   {
      return this.phase;
   }

   public void setPhase(java.lang.String phase)
   {
      this.phase = phase;
   }

   public java.lang.String getMilestone()
   {
      return this.milestone;
   }

   public void setMilestone(java.lang.String milestone)
   {
      this.milestone = milestone;
   }

   public java.util.List<demo.Document> getDocuments()
   {
      return this.documents;
   }

   public void setDocuments(java.util.List<demo.Document> documents)
   {
      this.documents = documents;
   }

   public boolean isApproved()
   {
      return this.approved;
   }

   public void setApproved(boolean approved)
   {
      this.approved = approved;
   }

   public Evidence(java.lang.String phase, java.lang.String milestone,
         java.util.List<demo.Document> documents, boolean approved)
   {
      this.phase = phase;
      this.milestone = milestone;
      this.documents = documents;
      this.approved = approved;
   }

}